name: Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

# Disable all permissions by default, requiring explicit permission definitions for all jobs.
permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          # Allow caching, as this job can't write and doesn't produce any artifacts.
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: "2.5.1"
          cache: true
      - run: deno publish --dry-run

  changesets:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          # Disable package manager cache to so that other jobs can't poison the NPM cache.
          package-manager-cache: false
      - name: Install dependencies
        run: npm ci
      - name: Create release pull request or GitHub release
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          version: npm run bump
          publish: npm run tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: changesets
    if: needs.changesets.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tarball: ${{ steps.pack.outputs.tarball }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          # Disable package manager cache to so that other jobs can't poison the NPM cache.
          package-manager-cache: false
      - name: Install dependencies
        run: npm ci
      - name: Build & pack the package
        id: pack
        run: |
          npm run build
          TARBALL=$(npm pack)
          echo "tarball=${TARBALL}" >> ${GITHUB_OUTPUT}
      - name: Upload build artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: tarball
          path: ${{ steps.pack.outputs.tarball }}

  publish:
    environment: publish
    needs:
      - changesets
      - build
    if: needs.changesets.outputs.published == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
          # Disable package manager cache to so that other jobs can't poison the NPM cache.
          package-manager-cache: false
      - name: Download build artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: tarball
      - name: Publish to npm
        run: npm publish ${TARBALL}
        env:
          TARBALL: ${{ needs.build.outputs.tarball }}
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: "2.5.1"
          cache: false
      - name: Publish to jsr
        run: deno publish
